sudo: false
language: java
script: mvn test package
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: releases
  api_key:
    secure: "bea/Ysrv3bV0Fs3E6viMaoXtjQuX0OTjWzaW4DGXsbQJouWAqVZ9ZzOKTQeBoGDeON+qN5s4g1YRDgHiN2ZgyC9vYVCRq4qgkEvSEIiWZASDQyJtllLDWJ1lVQP7wu3etipRTGzLoKPngZOrYBcwzsxRIHDDi6mEaZsuZ+aSzSg="
  file: target/teamcity-microsoftsdks.zip
  on:
    repo: jozefizso/teamcity-microsoftsdks
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
